[theme]
base = "light"
primaryColor = "#1E90FF"            # أزرق سماوي للأزرار
backgroundColor = "#FFFFFF"         # خلفية بيضاء
secondaryBackgroundColor = "#F0F2F6" # رمادي فاتح للـ sidebar
textColor = "#000000"               # أسود للنصوص
font = "sans serif"

